volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    image: denisoid/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  
  frontend:
    image: denisoid/foodgram_frontend
    volumes:
      - static:/app/result_build/
    depends_on:
      - backend
  
  gateway:
    image: denisoid/foodgram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/staticfiles/
      - media:/media
    depends_on:
      - backend
      - frontend  